FROM nvidia/cuda:12.5.0-devel-ubuntu22.04

USER root
# 安装依赖
RUN apt update && apt install -y \
    curl sudo\
    python3 python3-pip

# 安装python依赖
RUN pip install jupyterhub notebook jupyterlab ipywidgets \
    jupyterhub-nativeauthenticator jupyterlab-language-pack-zh-CN jupyter_contrib_nbextensions \
    argparse torch numpy pandas scikit-learn matplotlib typing functoolsplus scipy
RUN pip install sympy mamba_ssm

# 安装代理
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash -  && \
    apt install -y nodejs &&\
    npm install -g configurable-http-proxy

# 创建用户脚本
RUN useradd -m -s /bin/bash admin && echo "admin:admin" | chpasswd

# 复制 JupyterHub 配置文件
COPY jupyterhub_config.py /srv/jupyterhub/jupyterhub_config.py

CMD ["jupyterhub", "-f", "/srv/jupyterhub/jupyterhub_config.py"]
